language: go

go:
  - 1.14.x

git:
  depth: 1

env:
  global:
    - GO111MODULE=on
    - KUBECONFIG=$HOME/.kube/config
    - IMG=keikoproj/addon-manager:latest

cache:
  directories:
    - $HOME/.local
    - $HOME/.kube

install:
  # install dependencies needed by jobs
  - wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.0/kubebuilder_2.3.0_linux_amd64.tar.gz
  - tar -zxvf  kubebuilder_2.3.0_linux_amd64.tar.gz
  - sudo mv kubebuilder_2.3.0_linux_amd64 /usr/local/kubebuilder

stages:
  - unit-test
  - docker-build
  - name: release
    if: NOT (type = pull_request) AND branch = master

jobs:
  include:

    - stage: unit-test
      script:
        - go test ./api/... ./controllers/... ./pkg/... ./cmd/... -coverprofile coverage.txt
        - bash <(curl -s https://codecov.io/bash)

    - stage: docker-build
      script:
        - if [ $TRAVIS_EVENT_TYPE = push ]; then export IMG=keikoproj/addon-manager:$TRAVIS_BRANCH; fi
        - docker build --no-cache -t ${IMG} .

    - stage: release
      script: curl -sL https://git.io/goreleaser | bash -s release --rm-dist
