language: go

go:
  - 1.17.x

git:
  depth: 1

services:
  - docker

env:
  global:
    - GO111MODULE=on
    - KUBECONFIG=$HOME/.kube/config
    - IMG=keikoproj/addon-manager:latest

cache:
  directories:
    - $HOME/.local
    - $HOME/.kube

before_install:
  # install dependencies needed by jobs
  - wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.2/kubebuilder_2.3.2_linux_amd64.tar.gz
  - tar -zxvf  kubebuilder_2.3.2_linux_amd64.tar.gz
  - sudo mv kubebuilder_2.3.2_linux_amd64 /usr/local/kubebuilder

install: skip

stages:
  - unit-test
  - build
  - name: snapshot-release
    if: NOT (type = pull_request) AND (tag IS NOT present) AND (branch = master)
  - name: release
    if: NOT (type = pull_request) AND (tag IS present) AND (branch = master)

jobs:
  include:

    - stage: unit-test
      script:
        - go test ./api/... ./controllers/... ./pkg/... ./cmd/... -coverprofile coverage.txt
        - bash <(curl -s https://codecov.io/bash)

    - stage: build
      script:
        - make docker-build

    - stage: snapshot-release
      script:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - export IMG=keikoproj/addon-manager
        - curl -sL https://git.io/goreleaser | bash -s release --rm-dist --snapshot
        - docker push ${IMG}:latest

    - stage: release
      script:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - curl -sL https://git.io/goreleaser | bash -s release --rm-dist
